### ISSUE TITLE
Improve planner speed

### ISSUE THREAD

**Issue by aserbremen** [NMBURobotics/vox_nav#26]
Hi, 
thanks for your work on 3D navigation. I am working on integrating vox_nav with [Multi-Robot-Graph-SLAM](https://github.com/aserbremen/Multi-Robot-Graph-SLAM). I implemented an "interactive" map server, which subscribes to a pointcloud topic from a live SLAM, using the following relevant parameters: 

```yaml
vox_nav_interactive_map_manager:
  ros__parameters:
    pointcloud_topic: "mrg_slam/map_points_service"                                  # If you are using a SLAM method that publishes pointclouds, you can use this topic
    # PCD PREPROCESS PARAMS
    pcd_map_downsample_voxel_size: 0.1                                        # Set to smaller if you do not want downsample pointclouds of the map
    apply_filters: True                                                      # Optional noise removal steps to apply to map
    remove_outlier_mean_K: 50                                                 # you can set it True and play with parameters if the map is noisy
    remove_outlier_stddev_threshold: 0.06
    remove_outlier_radius_search: 0.6
    remove_outlier_min_neighbors_in_radius: 5
    # COST REGRESSION CRITICS AND PARAMS
    uniform_sample_radius: 0.2
    surfel_radius: 0.6                                                       # Works as resolution of cost regression onto map
    max_allowed_tilt: 0.25                                                   # 1st Cost critic Any angle(radians) higher than this is marked as NON-traversable
    max_allowed_point_deviation: 0.25                                        # 2nd Cost critic Point deviation from plane, this could be viewed as roughness of each cell 
    max_allowed_energy_gap: 0.5                                              # 3rd Cost critic Max Energy in each cell, this is detemined by max height differnce between edge points of cell
    node_elevation_distance: 1.2                                             # According to cell_radius, cell centers are sampled from original point cloud map, they are elevated from the original cloud
    plane_fit_threshold: 0.1                                                 # when fitting a plane to each cell, a plane_fit_threshold is considered from plane fitting utility of PCL
    robot_mass: 0.1                                                          # approximate robot mass considering cell_radius, this isnt so important
    average_speed: 1.0                                                       # average robot speed(m/s) when calcuating kinetic energy m = 0.5 * (m * pow(v,2))
    cost_critic_weights: [0.45, 0.45, 0.1]                                   # Give weight to each cost critic when calculating final cost, see above 3 Cost Critic descriptions
    # PCD MAP IS CONVERTED TO OCTOMAP, THIS OCTOMAP IS THEN USED BY PLANNERS FOR
    # COLLISION CHECKING
    octomap_voxel_size: 0.4                                                  # determines resolution of Octomap
    publish_octomap_visuals: true
    octomap_point_cloud_publish_topic: "vox_nav/map_server/octomap_pointcloud"                  # sensor_msgs::msg::PoinCloud2 that represents octomap
    octomap_markers_publish_topic: "vox_nav/map_server/octomap_markers"                         # visualization_msgs::msg::MarkeArray that represents octomap
    non_traversable_pointcloud_publish_topic: "vox_nav/map_server/non_traversable_pointcloud"   # sensor_msgs::msg::PoinCloud2 that represents non-traversable points
    traversable_pointcloud_publish_topic: "vox_nav/map_server/traversable_pointcloud"           # sensor_msgs::msg::PoinCloud2 that represents traversable points
    map_frame_id: "map"                                                      # This should be consistent with Gloabl EKF node , in robot_localization
```

Next, I got the planner to work using the following relevant parameters: 

```yaml
vox_nav_planner_server_rclcpp_node:
  ros__parameters:
    planner_plugin: "SEPLanner"          # other options: "SE2Planner", "ElevationPlanner", "OptimalElevationPlanner"
    expected_planner_frequency: 1.0
    planner_name: "CForest"                            
    planner_timeout: 50.0
    interpolation_parameter: 0                         # set to 0 if you wanna disable interpolating and smooting, otherwise 25 is a good default value                    
    octomap_voxel_size: 0.4
    robot_body_dimens:
      x: 1.2
      y: 1.2
      z: 0.8
    #robot_mesh_path: "package://botanbot_description/meshes/base_simplified.stl" # leave empty if you do not have one, robot_mesh_path: ""
    robot_mesh_path: ""
    SE2Planner:
      # Available Planners Include: PRMstar,LazyPRMstar,RRTstar,RRTsharp,RRTXstatic,InformedRRTstar,BITstar, 
                                 #  ABITstar,AITstar,CForest,LBTRRT,SST,TRRT,SPARS,SPARStwo,FMT,AnytimePathShortening
      plugin: "vox_nav_planning::SE2Planner"         # CForest: Reccomended
      se2_space: "REEDS"                             # "DUBINS","REEDS", "SE2" ### PS. Use DUBINS OR REEDS for Ackermann
      z_elevation: 0.8                               # Elevation of robot from ground plane, robot should not collide with plane                                      
      rho: 1.0                                       # Curve radius form reeds and dubins only
      state_space_boundries: 
        minx: -100.0
        maxx: 100.0
        miny: -100.0
        maxy: 100.0
        minyaw: -3.14
        maxyaw: 3.14
```

See this image, which I think is a satisfying result: 

![Image](https://github.com/user-attachments/assets/68793f72-9b3e-453a-937b-770613b312eb)

In the above case there are 9677 traversable points and 13091 non-traversable points

However, planning with a satisfying result takes a very long time 50-100 seconds. Can you give some insights on what parameters to tune to increase planning time? Also which planners do you recommend in general (most likely single surface scenario) and wrt. to fast processing times?
